apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleci-demo-java-spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleci-demo-java-spring
  template:
    metadata:
      labels:
        app: circleci-demo-java-spring
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: circleci-demo-java-spring
        image: mresetar.azurecr.io/circleci-demo:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: circleci-demo-java-spring-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: circleci-demo-java-spring